cloudcannon:
  data: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:path

# Collections configurations
collections:
  portfolios:
    output: true
    permalink: /:path

uploads_dir: /assets/images

# Default layouts
defaults:
  -
    scope:
      path: ""
      type: "portfolios"
    values:
      layout: "portfolio"
      _options:
        title:
        description_text:
        feature_image:          
        gallery:
          - size:
            frame_image:
          

# Enabled plugins. Uncomment them here and update the Gemfile, then run 'bundle install' on your terminal to enable them.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-responsive-image

# Plugin configurations
  # Configuration of WebP converter plugin
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/", "assets/images", "/assets/images/srcset"]
  nested: true
  regenerate: false

  # Configuration of the jekyll-responsive-image plugin
responsive_image:
  template: _includes/templates/image.html
  sizes:
    - width: 360
    - width: 480
    - width: 600
    - width: 960
    - width: 1400
  base_path: assets/images
  output_path_format: assets/images/srcset/%{width}/%{basename}

# Configuration of the compress_html layout
compress_html:
  comments: all  

# Background classes for the sections
background_classes:
  - bg-primary
  - bg-secondary
  - bg-accent
  - bg-reset

# Image sizes for gallery
sizes:
  - full-width
  - half-width
  - one-third
  - two-thirds
logo_versions:
  - light
  - dark  

_comments:
  font_family_embed_code_block: Load the Google Fonts and Fontawesome scripts here
  body_font_size_number: "Please specify 'rem' or 'px'"
  body_font_family: For all paragraphs, links and buttons
  heading_font_family: For all headings, subtitles and section intros
  gallery: Choose from the image sizes in order to build the gallery sections. Sizes are relative to the full width of the screen. All images will display full-screen on Mobile devices.
  

