cloudcannon:
  data: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:path

# Collections configurations
collections:
  portfolios:
    output: true
    permalink: /:path

uploads_dir: /assets/images

# Default layouts
defaults:
  -
    scope:
      path: "/portfolios"
      type: "portfolios"
    values:
      layout: "portfolio"
      _options:
        title:
        logo_version:
        description_text:
        feature_image:
        gallery:
          - size:
            frame_image:
          

# Enabled plugins. Uncomment them here and update the Gemfile, then run 'bundle install' on your terminal to enable them.
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-responsive-image

# Plugin configurations
  # Configuration of WebP converter plugin
webp:
  enabled: true
  quality: 75
  img_dir: ["/assets/images/", "assets/images", "/assets/images/srcset"]
  nested: true
  regenerate: false

  # Configuration of the jekyll-responsive-image plugin
responsive_image:
  template: _includes/templates/image.html
  sizes:
    - width: 360
    - width: 480
    - width: 600
    - width: 960
    - width: 1400
  base_path: assets/images
  output_path_format: assets/images/srcset/%{width}/%{basename}

# Configuration of the compress_html layout
compress_html:
  comments: all  

# Background classes for the sections
background_classes:
  - bg-primary
  - bg-secondary
  - bg-accent
  - bg-reset

# Image sizes for gallery
sizes:
  - full-width
  - half-width
  - one-third
  - two-thirds
logo_versions:
  - light
  - dark  

_comments:
  font_family_embed_code_block: 'As fontes precisam ser carregadas utilizando o "embed code" aqui.'
  body_font_size_number: "Please specify 'rem' or 'px'"
  body_font_family: Fonte dos parágrafos, links, e botões
  heading_font_family: Para os títulos e subtítulos de seção. 
  gallery: Escolha as imagens e construa a galeria de acordo com os tamanhos. 
  site_description_text: Otimizar este conteúdo para ferramentas de busca. Este conteúdo também será utilizado como preview nos compartilhamentos em redes sociais.
  site_title: O título do site é o conteúdo da aba do browser
  preview_image: Imagem que é utilizada quando compartilhar o site em redes sociais.
  header_image: Imagem para desktops & displays grandes
  mobile_header_image: Imagem para dispositiveis móveis. Optar por retrato.
  feature_image: A imagem principal do portfolio. É utilizada na homepage e também quando compartilha nas redes sociais.
  description_text: Otimizar este conteúdo para ferramentas de busca
  

