general:
  site_url: 'https://brunosantosphotography.com'
  address:
  email: brunosantosfotografia@gmail.com
  phone:
  instagram_url: 'https://instagram.com/brunosantosfotografia'
  instagram_handle: '@brunosantosfotografia'
  linkedin_url: 'https://www.linkedin.com/in/bruno-santos-fotógrafo-7244a371/'
branding:
  site_title: Bruno Santos
  nav_logo_light_image: /assets/images/bruno-santos-logo-light.png
  nav_logo_dark_image: /assets/images/bruno-santos-logo-dark.png
  footer_logo_image:
  preview_image: /assets/images/IMG_4155.jpg
theme_settings:
  primary_color: '#f2f2f2'
  secondary_color: '#000000'
  accent_color: '#182117'
  shade_color: '#465842'
  complementary_color: '#2f2f2f'
  font_family_embed_code_block:
  body_font_family: DINPro-light
  heading_font_family: DINPro-regular
  body_font_size_number: 1.1rem
  line_height_number: 1.8
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: true
      submenus:
        - name: Published
          url: /published
    - name: Portfolio
      url:
      is_dropdown: true
      submenus:
        - name: Beauty
          url: /beauty
        - name: Humanitarian
          url: /humanitarian
        - name: Abstract
          url: /abstract
        - name: fineart
          url: /fine-art
        - name: Portraits
          url: /portrait
    - name: Contact
      url: /contact
      is_dropdown: false
      submenus:
        - name:
          url:
seo:
  site_description_text: Retratos com verdade.
  keywords: 'portrait, luz natural, retratos'