general:
  site_url:
  address:
  email:
  phone:
  instagram_url: 'https://instagram.com/brunosantosfotografia'
  instagram_handle: '@brunosantosfotografia'
  linkedin_url: 'https://linkedin.com/bruno.santos'
branding:
  site_title: Bruno Santos
  nav_logo_image: /assets/images/bruno_OK-02 cópia.png
  footer_logo_image:
  preview_image:
theme_settings:
  primary_color: '#f2f2f2'
  secondary_color: '#000000'
  accent_color: '#182117'
  shade_color: '#465842'
  complementary_color: '#2f2f2f'
  font_family_embed_code_block:
  body_font_family: DINPro-regular
  heading_font_family: DINPro-light
  body_font_size_number: 1.1rem
  line_height_number: 1.8
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: false
      submenus:
        - name:
          url:
    - name: Portfolio
      url: /portfolio
      is_dropdown: true
      submenus:
        - name: Portraits
          url: /portraits
        - name: Humanitarian
          url: /humanitarian
        - name: Abstract
          url: /abstract
seo:
  site_description_text: Bruno Santos melhor fotógrafo do BRasillll
  keywords: 'portrait, luz natural, retratos'