general:
  site_url: 'https://brunosantosphoto.com'
  address:
  email: info@brunosantosphoto.com
  phone:
  instagram_url: 'https://instagram.com/brunosantosfotografia'
  instagram_handle: '@brunosantosfotografia'
  linkedin_url: 'https://www.linkedin.com/in/bruno-santos-fotógrafo-7244a371'
branding:
  site_title: Bruno Santos
  nav_logo_light_image: /assets/images/bruno-santos-logo-light.png
  nav_logo_dark_image: /assets/images/bruno-santos-logo-dark.png
  footer_logo_image:
  preview_image: /IMG_0051.jpg
theme_settings:
  primary_color: '#f2f2f2'
  secondary_color: '#000000'
  accent_color: '#182117'
  shade_color: '#131412'
  complementary_color: '#2f2f2f'
  font_family_embed_code_block:
  body_font_family: '''DINPro-light'', ''DINPRO'', sans-serif'
  heading_font_family: '''DINPro-regular'', ''DINPRO'', sans-serif'
  body_font_size_number: 1.1rem
  line_height_number: 1.8
navigation:
  menus:
    - name: About
      url: /about
      is_dropdown: true
      submenus:
        - name: Published
          url: /published
    - name: Portfolio
      url:
      is_dropdown: true
      submenus:
        - name: Beauty
          url: /beauty
        - name: Humanitarian
          url: /humanitarian
        - name: Portraits
          url: /portrait
        - name: Abstract
          url: /abstract
        - name: fineart
          url: /fine-art
    - name: Contact
      url: 'mailto:info@brunosantosphoto.com?subject=Contato'
      is_dropdown: false
      submenus:
        - name:
          url:
seo:
  site_description_text: |-
    True portraits.
    Lights and shadows.
  keywords: 'portrait, natural light, retratos, luz e sombra'